import Cart from '../components/Cart/Cart';
import Layout from '../components/Layout/Layout';
import Products from '../components/Shop/Products';
import Head from 'next/head'
import { useSelector, useDispatch } from "react-redux"
import { useEffect } from 'react';
import Notification from "../components/UI/Notification"
import { sendCartData, fetchCartData } from "../store/cart-actions"
let isInitial = true

function Index() {
  const dispatch = useDispatch()

  const showCart = useSelector(state => state.ui.cartIsVisisble)
  const cart = useSelector(state => state.cart)
  const notification = useSelector(state => state.ui.notification)

  useEffect(() => {
    //fetch data runs once 
    dispatch(fetchCartData())
  }, [dispatch])

  useEffect(() => {
    if (isInitial) {
      isInitial = false
      return
    }

    if (cart.changed) {
      dispatch(sendCartData(cart))
    }

  }, [cart, dispatch])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {notification &&
        <Notification
          status={notification.status}
          title={notification.title}
          message={notification.message} />}
      <Layout>
        {showCart && <Cart />}
        <Products />
      </Layout>
    </>
  );
}

export default Index;
